### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by whyjonii06** [iliran11/facebook-login-vue#14]
Hi,

I don't know what i'm doing wrong, can you help me please ?

In my Connexion.vue

import facebookLogin from 'facebook-login-vuejs'
export default {
  name: 'facebookLogin',
  component: {
    facebookLogin
  },
  data () {
    return {
      msg: 'Se connecter'
    }
  },
  methods: {
    getUserData: function() {
      this.FB.api('/me', 'GET', { fields: 'id,name,email' },
        userInformation => {
          this.personalID = userInformation.id;
          this.email = userInformation.email;
          this.name = userInformation.name;
        }
      )
    },
    sdkLoaded: function(payload) {
      this.isConnected = payload.isConnected
      this.FB = payload.FB
      if (this.isConnected) this.getUserData()
    },
    onLogin: function() {
      this.isConnected = true
      this.getUserData()
    },
    onLogout: function() {
      this.isConnected = false;
    }
  }
}

What's wrong ?

Thanks for help.

**Comment by adi518** [comment]
Use [this](https://github.com/adi518/vue-facebook-login-component) instead.
