### ISSUE TITLE
Code on example doesn't work

### ISSUE THREAD

**Issue by gabrielsclimaco** [iliran11/facebook-login-vue#3]
Runned `yarn` and then `yarn run dev` and got the following error when trying to run the code on example folder. Tried this more than once.

![captura de tela de 2017-11-22 09-41-32](https://user-images.githubusercontent.com/8144779/33125991-eb5ffc22-cf69-11e7-9fbb-51c90fd98048.png)

**Comment by iliran11** [comment]
Hi @gabrielsclimaco ,
Have you tried to run the Demo directly from the example Folder?
You have to run `yarn start` from the root folder. It should work as i checked it now from a fresh clone.

i will remove the `package.json` from `example` folder to avoid confusions in the future.
Please feel free to re-open if the problem persist.

**Comment by holic-cl** [comment]
To run the example

1. need to clone the whole repo.
2. cd to "facebook-login-vue" folder and run "npm i"
3. cd to example folder and run "npm i" again.
4. npm run dev
