### ISSUE TITLE
[Vue warn]: Unknown custom element: <facebook-login> - did you register the component correctly? 

### ISSUE THREAD

**Issue by baykingsea** [iliran11/facebook-login-vue#5]
Hi, I am using your plugin in a laravel /vuejs app with vuejs as a stand alone client in the resources/assets/js directory.  I got the following error:

[Vue warn]: Unknown custom element: <facebook-login> - did you register the component correctly? For recursive components, make sure to provide the "name" option.   Below is my code:
in my component: 
<facebook-login class="button"
      appId="326022817735322"
      @login="getUserData"
      @logout="onLogout"
      @get-initial-status="getUserData">
    </facebook-login>
import VueAxios from 'vue-axios'
import axios from 'axios';
import Vue from 'vue'
import facebookLogin from 'facebook-login-vuejs';

Vue.component('my-component', {
    components: {
        facebookLogin
    }
});
export default{
    data () {
      return {
        user: ''
       
      }
    },
 methods: {
        getUserData: function() {
      this.FB.api('/me', 'GET', { fields: 'id,name,email' },
        userInformation => {
          this.personalID = userInformation.id;
          this.email = userInformation.email;
          this.name = userInformation.name;
        }
      )
    },
    sdkLoaded: function(payload) {
      this.isConnected = payload.isConnected
      this.FB = payload.FB
      if (this.isConnected) this.getUserData()
    },
    onLogin: function() {
      this.isConnected = true
      this.getUserData()
    },
    onLogout: function() {
      this.isConnected = false;
    }
}

**Comment by adi518** [comment]
Is it still relevant?

**Comment by sbasi5576** [comment]
Yes it is.

**Comment by baykingsea** [comment]
Yes, I am still having this issue.

**Comment by Highor** [comment]
Vue.component('my-component', {
components: {
facebookLogin
}
});

Change to 

Vue.component('facebookLogin', facebookLogin);

**Comment by adi518** [comment]
Sorry for not replying earlier with a solution. It seems @Highor found a solution. You registered the component as "my-component", but used another name in your markup, thus Vue doesn't know the component in the name as it appears in the example code. This is not an issue with the component.

**Comment by FER-YAMA-AXON** [comment]
Hi  is this working now?? in this line i have an error "this.FB.api('/me', 'GET', { fields: 'id,name,email' },"  TypeError: Cannot read properties of undefined (reading 'api'), Can somebody help me?
