### ISSUE TITLE
Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings

### ISSUE THREAD

**Issue by Highor** [iliran11/facebook-login-vue#9]
Hi,

I am getting this error in my android app when i run it:
Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings

I found this post: https://github.com/facebook/php-graph-sdk/issues/951 but i am not sure how to update the facebook sdk for this particular module.

I already changed the js.src = '//connect.facebook.net/en_US/sdk.js'; to  js.src = 'https://connect.facebook.net/en_US/sdk.js'; in helpers.js and facebook-login.js and still i got this error.

I also added localhost in app domain's in the dev of FB.

Thanks

**Comment by adi518** [comment]
That's a Facebook SDK error. Did you change the app id to **your** app id? you have to register an app, and pass its id to the component. This specific error means you didn't configure the app correctly for allowed domains. Anyway, it is not an issue with the component.
